### PR TITLE
fix for centering insult

### PR DESCRIPTION
**Pull request by sdetweil**
changed labels to make it less confusing (working on phrases, not words).. 

but the NET fix is that the block of insults <span>..........</span><span>.........</span), are ALL being used for the centering calculation, when only ONE is actually visible..

so, to fix THAT make them display:none; so they are not used in the calc, and toggle visibility as well as opacity.

tiny fixes for other classes to not set position:absolute, and set static part of message correctly..

### CODE REVIEW

**Comment by mykle1** [comment]
Sam, thanks again. As you know, I struggled with this and gave up.

You rock!

**Comment by mykle1** [comment]
Closed the PR before merging. Wondered why nothing changed! haha

**Comment by sdetweil** [comment]
read this  post, the reply with 117 up votes
https://stackoverflow.com/questions/7756926/difference-between-span-and-div-with-text-aligncenter

```
the difference is not between <span> and <div> specifically, but between inline and block elements. <span> defaults to being display:inline; whereas <div> defaults to being display:block
The difference in the way text-align:center works between the two is down to the width.

A block element defaults to being the width of its container. It can have its width set using CSS, but either way it is a fixed width.

An inline element takes its width from the size of its content text.
```

**Comment by mykle1** [comment]
Thank you Sam. Will do bro.

**Pull request merged**
